defmodule DarkZenithWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :dark_zenith

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  # Secure/http_only/SameSite=Lax session cookies (DESIGN.md: Security
  # Considerations); :secure_cookies is set in prod configuration.
  @session_options [
    store: :cookie,
    key: "_dark_zenith_key",
    signing_salt: "1FSpVC28",
    same_site: "Lax",
    http_only: true,
    secure: Application.compile_env(:dark_zenith, :secure_cookies, false)
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:peer_data, :x_headers, session: @session_options]],
    longpoll: [connect_info: [:peer_data, :x_headers, session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :dark_zenith,
    gzip: not code_reloading?,
    only: DarkZenithWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :dark_zenith
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Body caps per DESIGN.md API Contract Details: JSON requests accept at most
  # 1 MiB; multipart is used only for GPG key uploads with a 2 162 688-byte
  # total cap. RPM payloads never traverse Phoenix (direct-to-B2).
  plug Plug.Parsers,
    parsers: [:urlencoded, {:multipart, length: 2_162_688}, {:json, length: 1_048_576}],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  # Forwarded scheme headers are honored only from trusted proxies
  # (DESIGN.md: Security Considerations); anything else is stripped before
  # force_ssl sees it, so a direct HTTP client cannot spoof HTTPS.
  plug :normalize_forwarded_proto
  # Plug.Head rewrites HEAD to GET for routing; repository-serving download
  # responses need the original method to sign a method-specific B2 URL.
  plug :save_original_method
  plug Plug.Head

  defp normalize_forwarded_proto(conn, _opts) do
    trusted =
      Enum.any?(
        Application.get_env(:dark_zenith, :trusted_proxies) || [],
        fn {network, prefix} -> DarkZenith.ClientIp.in_cidr?(conn.remote_ip, network, prefix) end
      )

    if trusted do
      conn
    else
      conn
      |> Plug.Conn.delete_req_header("x-forwarded-proto")
      |> Plug.Conn.delete_req_header("cf-connecting-ip")
      |> Plug.Conn.delete_req_header("x-forwarded-for")
    end
  end

  defp save_original_method(conn, _opts) do
    Plug.Conn.put_private(conn, :dz_original_method, conn.method)
  end
  plug Plug.Session, @session_options
  plug DarkZenithWeb.Router
end
