defmodule DarkZenith.RepodataTest do
  use ExUnit.Case, async: true

  alias DarkZenith.Repodata
  alias DarkZenith.Repodata.{Filelists, Gzip, Other, Primary, Repomd}

  describe "empty documents" do
    test "primary.xml for zero packages is the canonical empty document" do
      xml = IO.iodata_to_binary(Primary.encode([]))

      assert xml ==
               ~s(<?xml version="1.0" encoding="UTF-8"?>\n) <>
                 ~s(<metadata xmlns="http://linux.duke.edu/metadata/common" ) <>
                 ~s(xmlns:rpm="http://linux.duke.edu/metadata/rpm" packages="0">\n) <>
                 ~s(</metadata>\n)
    end

    test "filelists.xml for zero packages is the canonical empty document" do
      xml = IO.iodata_to_binary(Filelists.encode([]))

      assert xml ==
               ~s(<?xml version="1.0" encoding="UTF-8"?>\n) <>
                 ~s(<filelists xmlns="http://linux.duke.edu/metadata/filelists" packages="0">\n) <>
                 ~s(</filelists>\n)
    end

    test "other.xml for zero packages is the canonical empty document" do
      xml = IO.iodata_to_binary(Other.encode([]))

      assert xml ==
               ~s(<?xml version="1.0" encoding="UTF-8"?>\n) <>
                 ~s(<otherdata xmlns="http://linux.duke.edu/metadata/other" packages="0">\n) <>
                 ~s(</otherdata>\n)
    end
  end

  describe "deterministic gzip" do
    test "identical input produces identical bytes" do
      input = "hello repodata"
      assert Gzip.compress(input) == Gzip.compress(input)
    end

    test "output decompresses to the input" do
      input = String.duplicate("abc123", 1000)
      assert :zlib.gunzip(Gzip.compress(input)) == input
    end

    test "header has zero mtime and no original filename" do
      <<0x1F, 0x8B, 8, flg, mtime::little-32, _xfl, _os, _rest::binary>> =
        Gzip.compress("payload")

      assert mtime == 0
      # FNAME flag (bit 3) unset: no original filename stored.
      assert Bitwise.band(flg, 0b1000) == 0
    end
  end

  describe "repomd.xml" do
    test "contains revision and one data entry per artifact" do
      generation = Repodata.generate([], revision: 42, timestamp: 1_756_500_000)
      repomd = generation.repomd_xml

      assert repomd =~ ~s(<repomd xmlns="http://linux.duke.edu/metadata/repo">)
      assert repomd =~ "<revision>42</revision>"

      for type <- ["primary", "filelists", "other"] do
        assert repomd =~ ~s(<data type="#{type}">)
        assert repomd =~ ~s(<location href="repodata/#{type}.xml.gz"/>)
      end

      assert repomd =~ "<timestamp>1756500000</timestamp>"
    end

    test "checksums cover the exact generated bytes" do
      generation = Repodata.generate([], revision: 0, timestamp: 1_756_500_000)

      open_sha = :crypto.hash(:sha256, Primary.encode([])) |> Base.encode16(case: :lower)
      gz_sha = :crypto.hash(:sha256, generation.primary_xml_gz) |> Base.encode16(case: :lower)

      assert generation.repomd_xml =~
               ~s(<open-checksum type="sha256">#{open_sha}</open-checksum>)

      assert generation.repomd_xml =~ ~s(<checksum type="sha256">#{gz_sha}</checksum>)
    end

    test "sizes cover compressed and uncompressed byte counts" do
      generation = Repodata.generate([], revision: 0, timestamp: 1_756_500_000)

      open_size = IO.iodata_length(Primary.encode([]))
      gz_size = byte_size(generation.primary_xml_gz)

      assert generation.repomd_xml =~ "<size>#{gz_size}</size>"
      assert generation.repomd_xml =~ "<open-size>#{open_size}</open-size>"
      assert generation.open_sizes.primary == open_size
    end
  end

  describe "generate/2" do
    test "is fully deterministic for the same inputs" do
      a = Repodata.generate([], revision: 7, timestamp: 1_756_500_000)
      b = Repodata.generate([], revision: 7, timestamp: 1_756_500_000)

      assert a == b
    end

    test "empty open sizes are exposed for repository counter defaults" do
      generation = Repodata.generate([], revision: 0, timestamp: 1_756_500_000)

      assert generation.open_sizes.primary == IO.iodata_length(Primary.encode([]))
      assert generation.open_sizes.filelists == IO.iodata_length(Filelists.encode([]))
      assert generation.open_sizes.other == IO.iodata_length(Other.encode([]))
    end
  end

  describe "XML escaping" do
    test "text and attribute values are escaped" do
      assert IO.iodata_to_binary(DarkZenith.Repodata.XML.escape(~s(a<b>&"c'))) ==
               "a&lt;b&gt;&amp;&quot;c&#39;"
    end
  end
end
