import Config

# Configure your database
#
# Dev/test use the dedicated `dark-zenith-pg` podman container on host
# port 55432 (see README.md), leaving the machine's default 5432 free.
config :dark_zenith, DarkZenith.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "127.0.0.1",
  port: 55432,
  database: "dark_zenith_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Open registration in development for convenience.
config :dark_zenith, registration_enabled: true

# Root key material for token hashing and the GPG-key encryption envelope
# (DESIGN.md: Token storage; GPG private key encryption). Mirrors the endpoint
# secret_key_base so domain code does not depend on the web layer.
config :dark_zenith,
  secret_key_base: "iZXa64mMwQFKaq2gyY3jB2o16Ul9Pk8MVoNfX2A7ijW6oql/FA8xyvJg8jo/19l0"

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :dark_zenith, DarkZenithWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  # Default to 4100 locally (4000 is commonly taken by other projects on this
  # machine); PORT still overrides via runtime.exs.
  http: [ip: {127, 0, 0, 1}, port: 4100],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "iZXa64mMwQFKaq2gyY3jB2o16Ul9Pk8MVoNfX2A7ijW6oql/FA8xyvJg8jo/19l0",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:dark_zenith, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:dark_zenith, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :dark_zenith, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
