import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :dark_zenith, DarkZenithWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# TLS redirect + HSTS. The endpoint plugs Plug.SSL itself (after the
# untrusted forwarded-header strip) when this compile-time flag is set;
# PHX_SCHEME=http deployments exclude every request at runtime (DESIGN.md:
# Security Considerations). The endpoint's :force_ssl option is deliberately
# unused — Phoenix would plug it ahead of the header strip.
config :dark_zenith, enforce_tls: true

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

# Boot checks refuse startup on an unusable RPM toolchain (DESIGN.md:
# Deployment).
config :dark_zenith, boot_checks_on_boot: true

